---
title: "ECO 395 Homework 1 - Ahmed Almezail"
author: "Ahmed Almezail aia832"
date: "Feb 11, 2022"
output: md_document
---

library(tidyverse)
library(ggplot2)
library(data.table)
library(dplyr)


##PartA

billboard = billboard %>%
  select(performer, song, year, week, week_position, song_id, weeks_on_chart) 

top_songs = billboard %>%
  group_by(performer, song)

  
  
  yes = top_songs %>%
    tally() %>%
    arrange(desc(n)) %>%
    data.frame() %>%
    top_n(10, wt=n)
  
  colnames(yes)[3] <- "count"
  
  view(yes)
  
  #As we can see, Radioactive by Imagine dragons is the most popular song according to the billboard.
  
  ##PartB
  
  div_songs = billboard %>%
    group_by(performer, song, year) %>%
  filter_all(all_vars(.!=1958 & .!=2021))
  
  view(div_songs)
  
  group_by_year <- 
    data.table(div_songs)[ , .(unique_songs = length(unique(song))), 
                     by = year] 
  
  ggplot(group_by_year, aes(x=year)) + 
    geom_line(aes(y = unique_songs), color = "darkred") +
    labs(x="Year",
         y="number of unique songs",
         title="Musical Diversity",
         subtitle = "The number of unique songs appeared on the Billboard by the year",
         caption = "We can notice how in the 60's, the music diversity was increasing
         reaching 800 uniqe songs in a year. However, the number started to fall sharply
         from the late 60's to the end of the century with almost half of the peak value giving it sharp negative trend. Afterward,
         with the boom of the Pop music in the US, the diversity surged again reaching almost 600 songs in 2010.
         Then it fall again by about 100 in magnitude by 2014, then bounced back reaching the 800 level by 2020.
         This might be because of the rise of the social media, and the strong music marketing industry recently.")
  
  #PartC
 
 
 hit_songs = billboard %>%
   select(weeks_on_chart, performer, song) %>%
   group_by(performer, song) %>%
   summarize(count = n()) %>%
   arrange(desc(count)) %>%
   filter(count>=10)

 view(hit_songs)
 
 singers = hit_songs %>%
   group_by(performer) %>%
   summarize(count = n()) %>%
   filter(count >= 30) %>%
   arrange(desc(count))

 view(singers) 

 ggplot(singers) +
   geom_col(aes(fct_reorder(performer, count), count)) +
   coord_flip(expand = TRUE) +
   labs(x="Singers",
        title = "10-Week Hit!",
      caption = "As we can see, there are 19 singers who were able to have at least
      30 songs for a 10-week hit on the Billboard. Feel sorry for Imagine Dragons not to be in this list.")
  
  


